window.allModalRecipes = [
{
    idMeal: "22",
    modMeal: "Coconut Chocolate Muffins",
    modTime: "45min",
    modMealThumb: "img/id22coconutchocolatemuffins.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "105g sugar",
    modIngredient2: "1 egg (medium)",
    modIngredient3: "1 egg yolk",
    modIngredient4: "75g buttermilk",
    modIngredient4: "150g sour cream",
    modIngredient5: "2g vanilla extract",
    modIngredient6: "50g butter (melted and cooled)",
    modIngredient7: "zest of 1 lime",
    modIngredient8: "170g AP flour",
    modIngredient9: "4g salt",
    modIngredient10: "6g baking powder",
    modIngredient11: "2g baking soda",
    modIngredient12: "100g grated coconut",
    modIngredient13: "55g chopped white chocolate + extra for topping",
},
{
    idMeal: "21",
    modMeal: "BBQ Chicken Pizza",
    modTime: "3hr 20min",
    modMealThumb: "img/id21pizzabbq.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "BBQ sauce",
    modIngredient2: "120g Smoked gruyere, shredded",
    modIngredient3: "120g mozzarella, shredded",
    modIngredient4: "1 225g chicken breast filet",
    modIngredient4: "10-12 slices thick cut bacon",
    modIngredient5: "Sliced red onion",
    modIngredient6: "Chopped cilantro",
},
{
    idMeal: "20",
    modMeal: "Crème Brûlée",
    modTime: "4hr",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "600g high-fat cream (31%)",
    modIngredient2: "1 vanilla bean",
    modIngredient3: "3g vanilla extract",
    modIngredient4: "80g sugar",
    modIngredient5: "7 egg yolks",
    modIngredient6: "4g sugar",
},
{
    idMeal: "19",
    modMeal: "Sweet Brioche",
    modTime: "2hr",
    modMealThumb: "img/id19sweetbrioche.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "40g bread flour",
    modIngredient2: "200ml water",
    modIngredient3: "580g bread flour",
    modIngredient4: "60g sugar",
    modIngredient5: "12g salt",
    modIngredient6: "10g dry yeast",
    modIngredient7: "260g milk",
    modIngredient8: "1 egg (medium)",
    modIngredient9: "50g soften butter",
},
{
    idMeal: "18",
    modMeal: "Japanese Style Curry",
    modTime: "30min",
    modMealThumb: "img/id18japanesestylecurry.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "30g butter",
    modIngredient2: "15g AP flour",
    modIngredient3: "12g curry powder",
    modIngredient4: "300g chicken breast",
    modIngredient5: "250g potatoes",
    modIngredient6: "100g carrots",
    modIngredient7: "150g yellow onion",
    modIngredient8: "600ml chicken stock",
},
{
    idMeal: "17",
    modMeal: "Mushrooms & Onions Pizza",
    modTime: "3hr 20min",
    modMealThumb: "img/id17pizzamushroomandonions.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "250g gouda, shredded",
    modIngredient2: "Sliced pickled red onion",
    modIngredient3: "100g sliced and cooked mushrooms",
    modIngredient4: "120g mozzarella, shredded",
    modIngredient5: "pinch of salt",
},
{
    idMeal: "16",
    modMeal: "Quattro Formaggi Pizza",
    modTime: "3hr 20min",
    modMealThumb: "img/id16pizzaquattroformaggi.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "250g gouda, shredded",
    modIngredient2: "120g mozzarella, shredded",
    modIngredient3: "50g grated parmasan",
    modIngredient4: "25g pieces of blue cheese",
    modIngredient5: "pinch of salt",
},
{
    idMeal: "15",
    modMeal: "Chocolate Chip Cookies",
    modTime: "12hr 20min",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "180g AP flour",
    modIngredient2: "2g baking powder",
    modIngredient3: "3g baking soda",
    modIngredient4: "3g salt",
    modIngredient5: "115g soften butter",
    modIngredient6: "90g sugar",
    modIngredient7: "90g brown sugar",
    modIngredient8: "2 eggs (medium)",
    modIngredient9: "2g vanilla extract",
    modIngredient10: "225g chopped chocolate",
},
{
    idMeal: "14",
    modMeal: "Sponge Cherry Cake",
    modTime: "1hr",
    modMealThumb: "img/id14spongecherrycake.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "200g sugar",
    modIngredient2: "8g vanilla sugar",
    modIngredient3: "4 eggs (medium)",
    modIngredient4: "100g sunflower oil",
    modIngredient5: "100g milk",
    modIngredient6: "290g semi coarse flour",
    modIngredient7: "9g baking powder",
    modIngredient8: "300g pitted cherries",
},
{
    idMeal: "13",
    modMeal: "Czech Bacon Dumplings",
    modTime: "30min",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "330g smoked pork belly",
    modIngredient2: "100g bakon, sliced and chopped",
    modIngredient3: "600g white bread",
    modIngredient4: "200g coarse flour",
    modIngredient5: "20g salt",
    modIngredient6: "2 eggs (medium)",
    modIngredient7: "pinch of ground black pepper",
    modIngredient8: "500ml milk",
    modIngredient9: "600g finely chopped yellow onion",
    modIngredient10: "500g sauerkraut",
},
{
    idMeal: "12",
    modMeal: "Smash Burger",
    modTime: "20min",
    modMealThumb: "img/id12smashburger.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "2 burger buns",
    modIngredient2: "200g minced meat",
    modIngredient3: "2 slices of cheddar cheese",
    modIngredient4: "120g lettuce",
    modIngredient5: "60g sliced yellow onion",
    modIngredient6: "splash of worcester sauce",
    modIngredient7: "40g ketchup",
    modIngredient8: "40g mustard",
    modIngredient9: "splash of pickle juice",
    modIngredient10: "pinch of salt",
    modIngredient10: "pinch of ground black pepper",
},
{
    idMeal: "11",
    modMeal: "Brownies",
    modTime: "1hr",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "100g AP flour",
    modIngredient2: "1g baking powder",
    modIngredient3: "4g salt",
    modIngredient4: "30g olive oil",
    modIngredient5: "115g butter",
    modIngredient6: "150g sugar",
    modIngredient7: "50g brown sugar",
    modIngredient8: "200g chopped chocolate",
    modIngredient9: "50g cocoa powder",
    modIngredient10: "5g vanilla extract",
    modIngredient11: "3 eggs (medium)",
},
{
    idMeal: "10",
    modMeal: "Stuffed Crust Pizza",
    modTime: "3hr 20min",
    modMealThumb: "img/id10stuffedcrustpizza.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "270ml water (30 C°)",
    modIngredient2: "5g dry yeast",
    modIngredient3: "35g sugar",
    modIngredient4: "30g olive oil",
    modIngredient5: "450g AP flour",
    modIngredient6: "12g salt",
},
{
    idMeal: "9",
    modMeal: "One Hour Dough Pizza",
    modTime: "1hr",
    modMealThumb: "img/id9onehourdoughpizza.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "210ml water or beer (36 C°)",
    modIngredient2: "350g AP flour",
    modIngredient3: "5g salt",
    modIngredient4: "8g sugar",
    modIngredient5: "7g dry yeast",
    modIngredient6: "15g olive oil",
},
{
    idMeal: "8",
    modMeal: "Ultimate Pizza Dough",
    modTime: "3hr",
    modMealThumb: "img/id8ultimatepizzadough.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "200ml water (30 C°)",
    modIngredient2: "3g dry yeast",
    modIngredient3: "10g sugar",
    modIngredient4: "10g olive oil",
    modIngredient5: "340g AP flour",
    modIngredient6: "8g salt",
},
{
    idMeal: "7",
    modMeal: "Thai Green Curry",
    modTime: "30min",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "650g boneless skinless chicken thighs",
    modIngredient2: "10g salt",
    modIngredient3: "200g red bell pepper, chopped",
    modIngredient4: "100g snow peas, halved",
    modIngredient5: "75g serrano chiles or green bell pepper",
    modIngredient6: "30g shallot, chopped",
    modIngredient7: "30g garlic, chopped",
    modIngredient8: "30g lemongrass, chopped",
    modIngredient9: "3g cumin",
    modIngredient10: "3g coriander",
    modIngredient11: "1g turmeric",
    modIngredient12: "5g salt",
    modIngredient13: "10g cilantro",
    modIngredient14: "zest of 1 lime",
    modIngredient15: "50-75ml water",
    modIngredient16: "800g coconut milk",
    modIngredient17: "30g fish sauce",
    modIngredient18: "20g brown sugar",

},
{
    idMeal: "6",
    modMeal: "Cinnamon Rolls",
    modTime: "16hr 20min",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "115g butter",
    modIngredient2: "115ml milk",
    modIngredient3: "225g white jogurt",
    modIngredient4: "450g AP flour",
    modIngredient5: "100g sugar",
    modIngredient6: "5g dry yeast",
    modIngredient7: "8g salt",
    modIngredient8: "1g baking soda",
    modIngredient9: "115g soften butter",
    modIngredient10: "150g brown sugar",
    modIngredient11: "20g ground cinnamon",
    modIngredient12: "1g salt",
    modIngredient13: "115g soften cream cheese",
    modIngredient14: "2g vanilla extract",
    modIngredient15: "150g powdered sugar",
    modIngredient16: "zest of 1/2 lemon",
},
{
    idMeal: "5",
    modMeal: "Chicken Burger",
    modTime: "20min",
    modMealThumb: "img/noimgfound.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "2 burger buns",
    modIngredient2: "140g sliced chicken breast",
    modIngredient3: "120g AP flour",
    modIngredient4: "1 egg",
    modIngredient5: "splash of milk",
    modIngredient6: "pinch of salt",
    modIngredient7: "pinch of ground black pepper",
    modIngredient8: "cornplakes",
    modIngredient9: "100g mayonnaise",
    modIngredient10: "60g blue cheese",
    modIngredient11: "120g lettuce",
},
{
    idMeal: "4",
    modMeal: "Banana Walnut Muffins",
    modTime: "45min",
    modMealThumb: "img/id4bananawalnutmuffins.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "105g brown sugar",
    modIngredient2: "1 egg (medium)",
    modIngredient3: "1 egg yolk",
    modIngredient4: "20g maple syrup or honey",
    modIngredient4: "50g sunfower oil",
    modIngredient5: "50g buttermilk",
    modIngredient7: "140g sour cream",
    modIngredient7: "2g vanilla extract",
    modIngredient9: "130g soften banana, mashed",
    modIngredient10: "170g AP flour",
    modIngredient11: "4g salt",
    modIngredient12: "6g baking powder",
    modIngredient13: "2g baking soda",
    modIngredient14: "55g toasted chopped walnuts",
    modIngredient15: "25g raw chopped walnuts for topping",

},
{
    idMeal: "3",
    modMeal: "Double Chocolate Muffins",
    modTime: "45min",
    modMealThumb: "img/id3doublechocolatemuffins.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "150g sugar",
    modIngredient2: "1 egg (medium)",
    modIngredient3: "1 egg yolk",
    modIngredient4: "50g sunfower oil",
    modIngredient5: "50g buttermilk",
    modIngredient6: "170g sour cream",
    modIngredient7: "2g vanilla extract",
    modIngredient8: "170g AP flour",
    modIngredient9: "4g salt",
    modIngredient10: "6g baking powder",
    modIngredient11: "2g baking soda",
    modIngredient12: "25g cocoa powder",
    modIngredient13: "55g chopped chocolate + extra for topping",
},
{
    idMeal: "2",
    modMeal: "Blueberry Muffins",
    modTime: "45min",
    modMealThumb: "img/id2blueberrymuffins.jpg",
    modInmoductions: "FILL THE DIRECTIONS HERE",
    modIngredient1: "105g sugar",
    modIngredient2: "1 egg (medium)",
    modIngredient3: "1 egg yolk",
    modIngredient4: "75g buttermilk",
    modIngredient5: "112g sour cream",
    modIngredient6: "1g vanilla extract",
    modIngredient7: "25g sunflower oil",
    modIngredient8: "25g butter (melted and cooled)",
    modIngredient9: "185g AP flour",
    modIngredient10: "4g salt",
    modIngredient11: "6g baking powder",
    modIngredient12: "22g baking soda",
    modIngredient13: "140g fresh or frozen blueberries",
    modIngredient14: "lemon sugar (25g brown sugar + zest of 1/2 lemon, mixed)",
},
{
    idMeal: "1",
    modMeal: "Burger buns",
    modTime: "3hr 45min",
    modMealThumb: "img/id1burgerbuns.jpg",
    modInmoductions: "First of all, we will mix the 'Tangzhong'. Into the stainless steel pot we combine milk, water and flour. Whisk that together to get it incorporated, then place that pot over medium heat and continuously whisk, until the paste thickens dramatically. This whole process should take only about 2 or 3 minutes, but be careful, because the paste starts to get thicken about 25-30 seconds. Then take 120g milk heated to about 35 degrees Celsius and add 9g of dry yeast, mix it and let that sit for about 8 minutes. Then combine in the bowl of a stand mixer 320g bread flour, 7g of salt and 35g of sugar. Give that a quick whisk unlit thouroughly incorporated. Now, with your stand mixer running on low speed, add your milk with yeast mixure. Let that run for a fex seconds and then add 'Tangzhong' paste from earlier, followed by 1 whole egg and 1 egg yolk. After that increase mixer speed to medium-low and then mix all that together untlit thoroughly incorporated. Once incorporated, gradually add 42g of soften butter, then let that stand mixer knead the dough for about 10 more minutes. Then take the dought and gently fold in the sides and then place that seam side down on a work surface and rub it aroung in a circle with your hands keeping constant contact with the board. Once it's into a nice ball shape, place it in oil greased bowl and let the dough slowly rise in the fridge overnight. Next day, pull the dough out and let it get back to the room temerature. After that, give the dough some good old fist punch, then lightly flour a work surface and dump your dough out. using a bench scraper and scale divide your dough into six even pieces and seventh smaller one. Each piece should be around 95 to 105g. Now it's time for shaping. Grap a edge section of a dough and genttly stretch and fold it to the center, repeat that process around the whole segment of dough 5 more times, then flip it over and give it tension by pulling the dough towards you, keeping constant contact with the work surface. Repeat this process with all your dough pieces. After that, place your balls evenly spaced apart on a rimmed baking sheet tray lined with lightly greased parchment paper, each ball should be spaced apart about 6 centimetres apart. Then place another equally sized baking sheet tray inverted on top of these, so they don't dry out and allow them to rise to room temerature for one to two more hours. Preheat your oven to 190 C°. Then make an egg wash consisting of one egg and a splash of milk. Whisk together nicely, then gently brush the entire top of the buns with egg wash. You can optionaly use sesame seeds for topping, then place your buns in the preheated oven for 18 minutes. After that, remove now golden buns from the oven and brush each one generously with melted butter.",
    modIngredient1: "60ml milk",
    modIngredient2: "27ml water",
    modIngredient3: "20g bread flour",
    modIngredient4: "120ml warm milk (35 C°)",
    modIngredient5: "9g dry yeast",
    modIngredient6: "320g bread flour",
    modIngredient7: "7g salt",
    modIngredient8: "35g sugar",
    modIngredient9: "1 egg (medium)",
    modIngredient10: "1 egg yolk",
    modIngredient11: "42g soften butter",
},
]