window.allModalRecipes = [
{
    idMeal: "1",
    modMeal: "Burger buns",
    modTime: "3hr 45min",
    modMealThumb: "../img/id1burgerbuns.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "2",
    modMeal: "Blueberry Muffins",
    modTime: "45min",
    modMealThumb: "../img/id2blueberrymuffins.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "3",
    modMeal: "Double Chocolate Muffins",
    modTime: "45min",
    modMealThumb: "../img/id3doublechocolatemuffins.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "4",
    modMeal: "Banana Walnut Muffins",
    modTime: "45min",
    modMealThumb: "../img/id4bananawalnutmuffins.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "5",
    modMeal: "Chicken Burger",
    modTime: "20min",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "6",
    modMeal: "Cinnamon Rolls",
    modTime: "16hr 20min",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "7",
    modMeal: "Thai Green Curry",
    modTime: "30min",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "8",
    modMeal: "Ultimate Pizza Dough",
    modTime: "3hr",
    modMealThumb: "../img/id8ultimatepizzadough.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "9",
    modMeal: "One Hour Dough Pizza",
    modTime: "1hr",
    modMealThumb: "../img/id9onehourdoughpizza.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "10",
    modMeal: "Stuffed Crust Pizza",
    modTime: "3hr 20min",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "11",
    modMeal: "Brownies",
    modTime: "1hr",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "12",
    modMeal: "Smash Burger",
    modTime: "20min",
    modMealThumb: "../img/id12smashburger.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "13",
    modMeal: "Czech Bacon Dumplings",
    modTime: "30min",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "14",
    modMeal: "Sponge Cherry Cake",
    modTime: "1hr",
    modMealThumb: "../img/id14spongecherrycake.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "15",
    modMeal: "Chocolate Chip Cookies",
    modTime: "12hr 20min",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "16",
    modMeal: "Quattro Formaggi Pizza",
    modTime: "3hr 20min",
    modMealThumb: "../img/id16pizzaquattroformaggi.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "17",
    modMeal: "Mushrooms & Onions Pizza",
    modTime: "3hr 20min",
    modMealThumb: "../img/id17pizzamushroomandonions.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "18",
    modMeal: "Japanese Style Curry",
    modTime: "30min",
    modMealThumb: "../img/id18japanesestylecurry.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "19",
    modMeal: "Sweet Brioche",
    modTime: "2hr",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "20",
    modMeal: "Crème Brûlée",
    modTime: "4hr",
    modMealThumb: "../img/noimgfound.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "soy sauce",
    modIngredient2: "water",
    modIngredient3: "brown sugar",
    modIngredient4: "ground ginger",
    modIngredient5: "minced garlic",
    modIngredient6: "cornstarch",
    modIngredient7: "chicken breasts",
    modIngredient8: "stir-fry vegetables",
    modIngredient9: "brown rice",
},
{
    idMeal: "21",
    modMeal: "BBQ Chicken Pizza",
    modTime: "3hr 20min",
    modMealThumb: "../img/id21pizzabbq.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "BBQ sauce",
    modIngredient2: "120g Smoked gruyere, shredded",
    modIngredient3: "120g Ful fat mozzarella, shredded",
    modIngredient4: "1 225g chicken breast filet",
    modIngredient4: "10-12 slices thick cut bacon",
    modIngredient5: "Sliced red onion",
    modIngredient6: "Chopped cilantro",

},
{
    idMeal: "22",
    modMeal: "Coconut Chocolate Muffins",
    modTime: "45min",
    modMealThumb: "../img/id22coconutchocolatemuffins.jpg",
    modInmoductions: "Preheat oven to 350° F. Spray a 9x13-inch baking pan with non-stick spray.\r\nCombine soy sauce, ½ cup water, brown sugar, ginger and garlic in a small saucepan and cover. Bring to a boil over medium heat. Remove lid and cook for one minute once boiling.\r\nMeanwhile, stir together the corn starch and 2 tablespoons of water in a separate dish until smooth. Once sauce is boiling, add mixture to the saucepan and stir to combine. Cook until the sauce starts to thicken then remove from heat.\r\nPlace the chicken breasts in the prepared pan. Pour one cup of the sauce over top of chicken. Place chicken in oven and bake 35 minutes or until cooked through. Remove from oven and shred chicken in the dish using two forks.\r\n*Meanwhile, steam or cook the vegetables according to package directions.\r\nAdd the cooked vegetables and rice to the casserole dish with the chicken. Add most of the remaining sauce, reserving a bit to drizzle over the top when serving. Gently toss everything together in the casserole dish until combined. Return to oven and cook 15 minutes. Remove from oven and let stand 5 minutes before serving. Drizzle each serving with remaining sauce. Enjoy!",
    modIngredient1: "BBQ sauce",
    modIngredient2: "120g Smoked gruyere, shredded",
    modIngredient3: "120g Ful fat mozzarella, shredded",
    modIngredient4: "1 225g chicken breast filet",
    modIngredient4: "10-12 slices thick cut bacon",
    modIngredient5: "Sliced red onion",
    modIngredient6: "Chopped cilantro",

},
]